#!/usr/bin/env bash
# Configure the user's shell to run airlock and its 3rd-party scanners:
#  - put bin/airlock on PATH
#  - export UV_EXCLUDE_NEWER so uvx-run scanners honor the 3-day cooldown
# Writes a sourceable env file and (optionally) wires it into the shell rc.
# Usage: shell-setup.sh
set -uo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
# shellcheck source=/dev/null
source "${ROOT}/scripts/lib/common.sh"
# shellcheck source=/dev/null
source "${ROOT}/scripts/lib/config.sh"

ui_header "airlock • shell setup"

config_home="${XDG_CONFIG_HOME:-$HOME/.config}/airlock"
env_file="${config_home}/env.sh"
mkdir -p "$config_home"

cat >"$env_file" <<EOF
# Generated by airlock shell-setup ($(date -u +%Y-%m-%dT%H:%M:%SZ)).
# Source this from your shell rc to use airlock and the 3-day supply-chain cooldown.
export PATH="${ROOT}/bin:\$PATH"
# Apply the cooldown to uvx-run scanners (semgrep, guarddog, heckler).
export UV_EXCLUDE_NEWER="${UV_EXCLUDE_NEWER}"
# Default severity gate for airlock (override per-run with AIRLOCK_GATE=...).
export AIRLOCK_GATE="${AIRLOCK_GATE}"
EOF

log_ok "wrote ${env_file}"
ui_note "Contents:"
cat "$env_file"

# Pick the most likely rc for the current login shell.
case "$(basename "${SHELL:-/bin/zsh}")" in
  zsh)  rc="${ZDOTDIR:-$HOME}/.zshrc" ;;
  bash) rc="$HOME/.bashrc" ;;
  *)    rc="$HOME/.profile" ;;
esac

source_line="source \"${env_file}\""
if [ -f "$rc" ] && grep -qF "$source_line" "$rc" 2>/dev/null; then
  log_ok "${rc} already sources the airlock env file"
  exit 0
fi

echo
if ui_confirm "Append a line to ${rc} so new shells load this automatically?"; then
  {
    printf '\n# Added by airlock shell-setup\n%s\n' "$source_line"
  } >>"$rc"
  log_ok "updated ${rc}"
  ui_note "Open a new terminal, or run:  source \"${env_file}\""
else
  ui_note "Skipped. To enable in the current shell now, run:  source \"${env_file}\""
fi
